version: "3"

services:
  #nginxbe
  qsserverbe:
    container_name: qsserverbe
    image: nginx:stable-alpine
    restart: always
    ports:
      - "6082:82"
    volumes:
      - ../syops:/var/www/syops
      - ../env:/var/www/env
      - ./nginxbe/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - scorpionet

  #phpbe
  qsbe:
    container_name: qsbe
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    volumes:
      - ../syops:/var/www/syops
      - ../env:/var/www/env
    networks:
      - scorpionet
  # #db
  qsdb:
    container_name: qsdb
    platform: linux/x86_64
    image: mysql:8
    # ports:
    #   - 9586:3306
    volumes:
      - qsdata:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_DATABASE: scorpio
      MYSQL_ROOT_PASSWORD: r00tadmin
    networks:
      - scorpionet

  qsadmin:
    container_name: qsadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: qsdb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 6084:80
    networks:
      - scorpionet

volumes:
  qsdata:
    driver: local

networks:
  scorpionet:
    name: scorpionet
